export const companies = [
  "Caterpillar",
  "HP",
  "SodaStream",
  "G4S",
  "Motorola Solutions",
  "Airbnb",
  "Puma",
  "Unilever (Ben & Jerry's)",
  "AWS",
  "Veolia",
  "Elbit Systems",
  "Booking.com",
  "AXA",
  "Estée Lauder",
  "General Mills",
  "Sabra",
  "Oracle",
  "Tripadvisor",
  "Hyundai Heavy Industries",
  "JCB",
  "Cemex",
  "RE/MAX",
  "BlackRock",
  "Mekorot",
  "Egged",
  "Hapoalim, Leumi",
  "Expedia",
  "Domino's Pizza",
  "McDonald's",
  "Papa John's",
  "Pizza Hut",
  "Burger King",
  "Accenture",
  "AccuWeather",
  "ActionIQ",
  "Adidas",
  "Alaska Air",
  "AllianceBernstein",
  "Allianz",
  "Amazon",
  "Amdocs",
  "American Airlines",
  "American Eagle",
  "American Express",
  "American Wire Group",
  "Amwell",
  "Apollo",
  "Apple",
  "ArentFox Schiff",
  "Atlassian",
  "Authentic Brands",
  "Avery Dennison",
  "Axel Springer",
  "Bain & Company",
  "Bank of America",
  "Bank of New York Mellon",
  "Bath & Body Works",
  "Baupost Group",
  "Bayer",
  "BCG",
  "Bioventus",
  "Blackrock",
  "Blackstone",
  "Bloomberg",
  "Boeing",
  "Bosch",
  "Bristol Myers Squibb",
  "Capri Holdings",
  "CareTrust REIT",
  "Chanel",
  "Chapman and Cutler",
  "Cisco",
  "Citadel",
  "Citi",
  "Comcast",
  "Compass",
  "Conde Nast",
  "CV Starr",
  "Cytokinetics",
  "Daimler",
  "Davis Polk",
  "Dell",
  "Deloitte",
  "Delta Air Lines",
  "Deutsche Bank",
  "Deutsche Telekom",
  "DHL Group",
  "Disney",
  "Douglas Elliman",
  "Edelman",
  "Eli Lilly",
  "Empyrean",
  "Endeavor",
  "Estee Lauder",
  "EY",
  "Forbes",
  "Fox Corp",
  "Gamida Cell",
  "GE",
  "General Catalyst",
  "General Motors",
  "Genesys",
  "Goldman Sachs",
  "Google",
  "Hearst",
  "Henkel",
  "Herbert Smith Freehills",
  "Hewlett Packard",
  "Hewlett Packard Enterprise",
  "HubSpot",
  "Huntsman Corp",
  "IBM",
  "Insight Partners",
  "Instacart",
  "Intel",
  "Intermedia",
  "Interpublic Group",
  "Intuit",
  "Jazwares",
  "Jefferies",
  "Johnson & Johnson",
  "JPMorgan",
  "Kenon Holdings",
  "KKR",
  "KPMG",
  "Lemonade",
  "Levi Strauss",
  "LinkedIn",
  "Live Nation Entertainment",
  "Major League Baseball",
  "Manpower Group",
  "Marsh & McLennan",
  "Mastercard",
  "Mattel",
  "McDermott Will & Emery",
  "McKinsey",
  "Merck",
  "Merck KGaA",
  "Meta",
  "MeUndies",
  "Microsoft",
  "Morgan Lewis",
  "Morgan Stanley",
  "MRC",
  "Nasdaq",
  "National Basketball Association",
  "NeoGames",
  "Netflix",
  "NFL",
  "Novartis",
  "Nvidia",
  "Okta",
  "Omnicom Group",
  "Palantir",
  "Paramount Global",
  "Paul Weiss",
  "Pershing Square",
  "Pfizer",
  "Phillips 66",
  "Pillsbury",
  "Progressive",
  "PVH",
  "PwC",
  "Queye",
  "Raytheon",
  "Regeneron Pharmaceuticals",
  "Related Companies",
  "Ribbon",
  "Riskified",
  "Salesforce",
  "SAP",
  "Sequoia Capital",
  "Seyfarth Shaw",
  "Siemens",
  "Simon Property Group",
  "Skydance",
  "Sony Music",
  "SoulCycle",
  "Stagwell",
  "Starbucks",
  "State Street",
  "Sullivan & Cromwell",
  "Sweetgreen",
  "Synovus",
  "Tesla",
  "Teva Pharmaceuticals",
  "Thermo Fisher Scientific",
  "Tieks by Gavrieli",
  "Tory Burch",
  "Troutman Pepper",
  "UBS",
  "United Airlines",
  "Universal Music Group",
  "UPS",
  "US Chamber of Commerce",
  "Verizon",
  "Volkswagen",
  "Vontier",
  "Walmart",
  "Warby Parker",
  "Warner Brothers Discovery",
  "Wells Fargo",
  "Winston & Strawn",
  "WWE",
  "Ziff Davis",
  "Zoom",
];
